name: synchronized_repo
description: Synchronized repo
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dev_dependencies:
  pedantic: '>=1.9.0 <3.0.0'
  process_run: '>=0.10.3'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.2.2'
  dev_test: '>=0.13.4+4'

