name: synchronized_repo_support
version: 0.1.0
publish_to: none
deploy_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  process_run: '>=0.10.0'
  path:
dev_dependencies:
  lints: '>=2.1.1'
  test: '>=1.0.0'
  dev_build: '>=0.16.2'