name: synchronized_repo_support
version: 0.1.0
publish_to: none
deploy_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  process_run: '>=0.10.0'
  path:
dev_dependencies:
  lints:
  test: '>=1.0.0'
  dev_test: '>=0.13.4-dev.1'
